"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['images/money-bag.icns', "drawer_counter.py", "tax_finder.py"]
OPTIONS = {
    'iconfile':'images/money-bag.icns',
}

setup(
    app=APP,
    name='Cash Counter',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
